# _config.yml
source: docs
destination: docs/_site

# Optionnel, mais utile pour le développement local
incremental: true

# Autres configurations utiles pour GitHub Pages
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-github-metadata
